# 1. Create a 3x3x3 array with random values

In [9]:
import numpy as np
arr1 = np.random.random((3,3,3))
print(arr1)
print("\n")

arr2 = np.arange(27).reshape((3,3,3))
print(arr2)

[[[0.54771208 0.99678334 0.07367049]
  [0.28566697 0.75041038 0.01692984]
  [0.52844558 0.06975921 0.5833707 ]]

 [[0.02321767 0.55029501 0.2753088 ]
  [0.8198153  0.31742059 0.1743385 ]
  [0.51185823 0.75093393 0.53252611]]

 [[0.07824782 0.00130532 0.90080867]
  [0.83453644 0.59563435 0.90448775]
  [0.40319531 0.91204191 0.07416812]]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [14]:
#https://numpy.org/doc/stable/reference/generated/numpy.diag.html

arr2 = np.diag([1,2,3,4],k=-1)
arr2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [34]:
arr3 = np.ones((8,8),dtype=int)
arr3[1:8:2,::2]=0
arr3[::2,1:8:2]=0
print(arr3)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4. Normalize a 5x5 random matrix

In [38]:
arr4= np.random.random((3,3))
print("Original Array:")
print(arr4)
arr4max, arr4min = arr4.max(), arr4.min()
arr4 = (arr4 - arr4min)/(arr4max - arr4min)
print("\n")
print("After normalization:")
print(arr4)

Original Array:
[[0.02758345 0.96936948 0.99766239]
 [0.90375625 0.17767789 0.88316009]
 [0.60000258 0.46932634 0.76191524]]


After normalization:
[[0.         0.97083443 1.        ]
 [0.90319743 0.15472394 0.881966  ]
 [0.5900748  0.45536798 0.75698147]]


# 5.  How to find common values between two arrays?

In [43]:
arr5 = np.array([0, 10, 20, 40, 60])
print("Array1:",arr5)
arr6 = np.array([10, 30, 40])
print("Array2:",arr6)
print("\n")
print("Common values between two arrays:")
print(np.intersect1d(arr5, arr6))

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]


Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [45]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday:",yesterday)
today = np.datetime64('today', 'D')
print("Today:",today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow:",tomorrow)

Yesterday: 2020-07-24
Today: 2020-07-25
Tomorrow: 2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [57]:
arr6 = ([[1,2,3,4],[5,6,7,8]])
arr7 = ([[1,2,3,4],[5,6,7,8]])
print(arr6)
print(arr7)
equal = np.allclose(arr6, arr7)
print(equal)
print("\n")
arr8 = np.random.randint(1,2,5)
arr9 = np.random.randint(1,2,5)
print(arr8)
print(arr9)

equal = np.allclose(arr8, arr9)
print(equal)

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1, 2, 3, 4], [5, 6, 7, 8]]
True


[1 1 1 1 1]
[1 1 1 1 1]
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [62]:
arr10 = np.random.random(10)
print(arr10)
arr10[arr10.argmax()] = 0
print("\n")
print(arr10)

[0.68862699 0.93114008 0.98791277 0.7268662  0.01898417 0.13488798
 0.74491645 0.8764488  0.730804   0.95520234]


[0.68862699 0.93114008 0.         0.7268662  0.01898417 0.13488798
 0.74491645 0.8764488  0.730804   0.95520234]


# 9. How to print all the values of an array?

In [67]:
import sys
arr11 = np.zeros((25,25))
print(arr11)
print("\n")
np.set_printoptions(threshold=sys.maxsize)
arr11 = np.zeros((25,25))
print(arr11)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

# 10.Subtract the mean of each row of a matrix

In [81]:
arr12 = np.random.random((5,5))
print("Original Array")
print(arr12)
print("\n")
print("Array of row means")
arr13 = arr12.mean(axis=1, keepdims = True)
print(arr13)
print("\n")
arr12 = arr12 - arr12.mean(axis=1, keepdims = True)
print("Array of original array - row mean")
print(arr12)
print("\n")

Original Array
[[0.17687164 0.11667346 0.55323781 0.47214385 0.37667743]
 [0.87847123 0.89479278 0.6169684  0.8187462  0.80387782]
 [0.94347349 0.8179069  0.71365091 0.69430042 0.01206475]
 [0.0794924  0.43791297 0.92662108 0.25156935 0.21076763]
 [0.12739182 0.08485006 0.17595727 0.52910995 0.48028562]]


Array of row means
[[0.33912084]
 [0.80257128]
 [0.6362793 ]
 [0.38127268]
 [0.27951894]]


Array of original array - row mean
[[-0.1622492  -0.22244738  0.21411697  0.13302301  0.03755659]
 [ 0.07589994  0.0922215  -0.18560289  0.01617491  0.00130654]
 [ 0.3071942   0.18162761  0.07737162  0.05802113 -0.62421455]
 [-0.30178029  0.05664028  0.54534839 -0.12970333 -0.17050506]
 [-0.15212712 -0.19466889 -0.10356167  0.24959101  0.20076668]]




# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [105]:
Z = np.ones(10)
print(Z)

I = np.random.randint(0,len(Z),20)
print(I)
Z = Z+ np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4 7 7 7 1 4 0 4 3 8 9 1 2 2 7 8 2 4 6 6]
[2. 3. 4. 2. 5. 1. 3. 5. 3. 2.]


# 12.How to get the diagonal of a dot product?

In [86]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
print(A)
print("\n")
print(B)
print("\n")
print(np.dot(A, B))
np.diag(np.dot(A, B))

[[2 5 0]
 [0 0 0]
 [6 3 9]]


[[9 9 1]
 [5 2 2]
 [2 5 1]]


[[ 43  28  12]
 [  0   0   0]
 [ 87 105  21]]


array([43,  0, 21])

# 13.How to find the most frequent value in an array?

In [96]:
Z = np.random.randint(50,100,50)
print (Z)
Y=np.sort(Z)
print(Y)
print(np.bincount(Z))
print('rank:', np.bincount(Z).argmax())

[54 71 82 50 87 60 92 86 77 66 78 89 77 53 60 73 67 63 68 67 76 66 93 97
 72 71 87 64 95 77 87 65 97 61 91 97 52 84 72 91 90 85 61 61 92 89 89 71
 78 91]
[50 52 53 54 60 60 61 61 61 63 64 65 66 66 67 67 68 71 71 71 72 72 73 76
 77 77 77 78 78 82 84 85 86 87 87 87 89 89 89 90 91 91 91 92 92 93 95 97
 97 97]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 2 3 0 1 1 1 2 2 1 0 0 3 2 1
 0 0 1 3 2 0 0 0 1 0 1 1 1 3 0 3 1 3 2 1 0 1 0 3]
rank: 61


# 14.How to get the n largest values of an array

In [112]:
Z = np.random.randint(0,100000,1000)
np.random.shuffle(Z)
n = 10

print (Z[np.argsort(Z)[-n:]])


[99127 99169 99275 99382 99421 99555 99609 99669 99765 99838]


# 15.How to create a record array from a regular array?

In [115]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(Z)
print("\n")
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
